apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: snfj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: snfj
    app.kubernetes.io/part-of: byoc-app-frhs
  name: snfj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: snfj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: snfj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-oocs-tenant/byoc-app-frhs/snfj@sha256:586782b177606e3d16dcb65ea2d272f79637d194d818ef603b4a0d2ec171b473
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
